-- phpMyAdmin SQL Dump
-- version 4.0.4.1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: May 16, 2016 at 09:49 PM
-- Server version: 5.6.12
-- PHP Version: 5.5.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `movieflix`
--
CREATE DATABASE IF NOT EXISTS `movieflix` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `movieflix`;

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE IF NOT EXISTS `admin` (
  `userid` varchar(50) NOT NULL DEFAULT '',
  `password` varchar(50) DEFAULT NULL,
  `firstName` varchar(50) DEFAULT NULL,
  `lastName` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`userid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`userid`, `password`, `firstName`, `lastName`) VALUES
('admin', 'password', 'Srinath reddy', 'Kasarla');

-- --------------------------------------------------------

--
-- Table structure for table `comments`
--

CREATE TABLE IF NOT EXISTS `comments` (
  `email` varchar(50) DEFAULT NULL,
  `imdbid` varchar(50) DEFAULT NULL,
  `comment` varchar(500) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `comments`
--

INSERT INTO `comments` (`email`, `imdbid`, `comment`) VALUES
('srinath_reddyk@yahoo.com', 'tt0068646', 'Great movie one of the best'),
('srinath_reddyk@yahoo.com', 'tt0068646', 'best movie  have ever seen'),
('srinath_reddyk@yahoo.com', 'tt0068646', ''),
('srinath_reddyk@yahoo.com', 'tt0062622', ''),
('srinath_reddyk@yahoo.com', 'tt0068646', 'great'),
('srinath_reddyk@yahoo.com', 'tt0062622', 'great Movie'),
('srinath_reddyk@yahoo.com', 'tt0068646', '5'),
('srinath_reddyk@yahoo.com', 'tt0068646', '4'),
('srinath_reddyk@yahoo.com', 'tt0068646', '5'),
('srinath_reddyk@yahoo.com', 'tt0068646', '4'),
('srinath_reddyk@yahoo.com', 'tt0372784', 'great Movie');

-- --------------------------------------------------------

--
-- Table structure for table `Movie`
--

CREATE TABLE IF NOT EXISTS `Movie` (
  `imdbID` varchar(255) NOT NULL,
  `Actors` varchar(255) DEFAULT NULL,
  `Awards` varchar(255) DEFAULT NULL,
  `Country` varchar(255) DEFAULT NULL,
  `Director` varchar(255) DEFAULT NULL,
  `Genre` varchar(255) DEFAULT NULL,
  `Language` varchar(255) DEFAULT NULL,
  `Metascore` varchar(255) DEFAULT NULL,
  `Plot` varchar(255) DEFAULT NULL,
  `Poster` varchar(255) DEFAULT NULL,
  `Rated` varchar(255) DEFAULT NULL,
  `Released` varchar(255) DEFAULT NULL,
  `Runtime` varchar(255) DEFAULT NULL,
  `Title` varchar(255) DEFAULT NULL,
  `Type` varchar(255) DEFAULT NULL,
  `Writer` varchar(255) DEFAULT NULL,
  `Year` varchar(255) DEFAULT NULL,
  `imdbRating` varchar(255) DEFAULT NULL,
  `imdbVotes` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`imdbID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `Movie`
--

INSERT INTO `Movie` (`imdbID`, `Actors`, `Awards`, `Country`, `Director`, `Genre`, `Language`, `Metascore`, `Plot`, `Poster`, `Rated`, `Released`, `Runtime`, `Title`, `Type`, `Writer`, `Year`, `imdbRating`, `imdbVotes`) VALUES
('tt0062622', 'Keir Dullea, Gary Lockwood, William Sylvester, Daniel Richter', 'Won 1 Oscar. Another 13 wins & 7 nominations.', 'USA, UK', 'Stanley Kubrick', 'Mystery, Sci-Fi', 'English, Russian', '86', 'Humanity finds a mysterious, obviously artificial object buried beneath the Lunar surface and, with the intelligent computer H.A.L. 9000, sets off on a quest.', 'http://ia.media-imdb.com/images/M/MV5BNDYyMDgxNDQ5Nl5BMl5BanBnXkFtZTcwMjc1ODg3OA@@._V1_SX300.jpg', 'G', '15 May 1968', '149 min', '2001: A Space Odyssey', 'movie', 'Stanley Kubrick (screenplay), Arthur C. Clarke (screenplay)', '1968', '8.3', '396,824'),
('tt0068646', 'Marlon Brando, Al Pacino, James Caan, Richard S. Castellano', 'Won 3 Oscars. Another 23 wins & 27 nominations.', 'USA', 'Francis Ford Coppola', 'Crime, Drama', 'English, Italian, Latin', '100', 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.', 'http://ia.media-imdb.com/images/M/MV5BMjEyMjcyNDI4MF5BMl5BanBnXkFtZTcwMDA5Mzg3OA@@._V1_SX300.jpg', 'R', '24 Mar 1972', '175 min', 'The Godfather', 'movie', 'Mario Puzo (screenplay), Francis Ford Coppola (screenplay), Mario Puzo (novel)', '1972', '9.2', '1,085,001'),
('tt0095016', 'Bruce Willis, Bonnie Bedelia, Reginald VelJohnson, Paul Gleason', 'Nominated for 4 Oscars. Another 6 wins & 2 nominations.', 'USA', 'John McTiernan', 'Action, Thriller', 'English, German, Italian', '70', 'John McClane, officer of the NYPD, tries to save wife Holly Gennaro and several others, taken hostage by German terrorist Hans Gruber during a Christmas party at the Nakatomi Plaza in Los Angeles.', 'http://ia.media-imdb.com/images/M/MV5BMTY4ODM0OTc2M15BMl5BanBnXkFtZTcwNzE0MTk3OA@@._V1_SX300.jpg', 'R', '20 Jul 1988', '131 min', 'Die Hard', 'movie', 'Roderick Thorp (novel), Jeb Stuart (screenplay), Steven E. de Souza (screenplay)', '1988', '8.2', '558,583'),
('tt0099685', 'Robert De Niro, Ray Liotta, Joe Pesci, Lorraine Bracco', 'Won 1 Oscar. Another 37 wins & 31 nominations.', 'USA', 'Martin Scorsese', 'Biography, Crime, Drama', 'English, Italian', '89', 'Henry Hill and his friends work their way up through the mob hierarchy.', 'http://ia.media-imdb.com/images/M/MV5BMTY2OTE5MzQ3MV5BMl5BanBnXkFtZTgwMTY2NTYxMTE@._V1_SX300.jpg', 'R', '21 Sep 1990', '146 min', 'Goodfellas', 'movie', 'Nicholas Pileggi (book), Nicholas Pileggi (screenplay), Martin Scorsese (screenplay)', '1990', '8.7', '682,729'),
('tt0106179', 'Gillian Anderson, David Duchovny, Mitch Pileggi', 'Won 5 Golden Globes. Another 88 wins & 202 nominations.', 'USA, Canada', 'N/A', 'Drama, Mystery, Sci-Fi', 'English', 'N/A', 'Two FBI agents, Fox Mulder the believer and Dana Scully the skeptic, investigate the strange and unexplained while hidden forces work to impede their efforts.', 'http://ia.media-imdb.com/images/M/MV5BODM2NzAwMjgxNF5BMl5BanBnXkFtZTcwNzYwNjkzMQ@@._V1_SX300.jpg', 'TV-MA', '10 Sep 1993', '44 min', 'The X-Files', 'series', 'Chris Carter', '1993â€“2002', '8.7', '124,651'),
('tt0108052', 'Liam Neeson, Ben Kingsley, Ralph Fiennes, Caroline Goodall', 'Won 7 Oscars. Another 69 wins & 32 nominations.', 'USA', 'Steven Spielberg', 'Biography, Drama, History', 'English, Hebrew, German, Polish', '93', 'In Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.', 'http://ia.media-imdb.com/images/M/MV5BMzMwMTM4MDU2N15BMl5BanBnXkFtZTgwMzQ0MjMxMDE@._V1_SX300.jpg', 'R', '04 Feb 1994', '195 min', 'Schindler''s List', 'movie', 'Thomas Keneally (book), Steven Zaillian (screenplay)', '1993', '8.9', '808,194'),
('tt0108778', 'Jennifer Aniston, Courteney Cox, Lisa Kudrow, Matt LeBlanc', 'Won 1 Golden Globe. Another 68 wins & 204 nominations.', 'USA', 'N/A', 'Comedy, Romance', 'English', 'N/A', 'Follows the lives of six 20-something friends living in Manhattan.', 'http://ia.media-imdb.com/images/M/MV5BMTg4NzEyNzQ5OF5BMl5BanBnXkFtZTYwNTY3NDg4._V1._CR24,0,293,443_SX89_AL_.jpg_V1_SX300.jpg', 'TV-14', '22 Sep 1994', '22 min', 'Friends', 'series', 'David Crane, Marta Kauffman', '1994â€“2004', '9.0', '433,690'),
('tt0109830', 'Tom Hanks, Rebecca Williams, Sally Field, Michael Conner Humphreys', 'Won 6 Oscars. Another 37 wins & 51 nominations.', 'USA', 'Robert Zemeckis', 'Drama, Romance', 'English', '82', 'Forrest Gump, while not intelligent, has accidentally been present at many historic moments, but his true love, Jenny Curran, eludes him.', 'http://ia.media-imdb.com/images/M/MV5BMTI1Nzk1MzQwMV5BMl5BanBnXkFtZTYwODkxOTA5._V1_SX300.jpg', 'PG-13', '06 Jul 1994', '142 min', 'Forrest Gump', 'movie', 'Winston Groom (novel), Eric Roth (screenplay)', '1994', '8.8', '1,167,104'),
('tt0110912', 'Tim Roth, Laura Lovelace, John Travolta, Samuel L. Jackson', 'Won 1 Oscar. Another 53 wins & 58 nominations.', 'USA', 'Quentin Tarantino', 'Crime, Drama', 'English, Spanish, French', '94', 'The lives of two mob hit men, a boxer, a gangster''s wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 'http://ia.media-imdb.com/images/M/MV5BMTkxMTA5OTAzMl5BMl5BanBnXkFtZTgwNjA5MDc3NjE@._V1_SX300.jpg', 'R', '14 Oct 1994', '154 min', 'Pulp Fiction', 'movie', 'Quentin Tarantino (story), Roger Avary (story), Quentin Tarantino', '1994', '8.9', '1,235,868'),
('tt0111161', 'Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler', 'Nominated for 7 Oscars. Another 14 wins & 20 nominations.', 'USA', 'Frank Darabont', 'Crime, Drama', 'English', '80', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 'http://ia.media-imdb.com/images/M/MV5BODU4MjU4NjIwNl5BMl5BanBnXkFtZTgwMDU2MjEyMDE@._V1_SX300.jpg', 'R', '14 Oct 1994', '142 min', 'The Shawshank Redemption', 'movie', 'Stephen King (short story "Rita Hayworth and Shawshank Redemption"), Frank Darabont (screenplay)', '1994', '9.3', '1,590,699'),
('tt0112573', 'James Robinson, Sean Lawlor, Sandy Nelson, James Cosmo', 'Won 5 Oscars. Another 25 wins & 27 nominations.', 'USA', 'Mel Gibson', 'Biography, Drama, History', 'English, French, Latin, Scottish Gaelic', '68', 'When his secret bride is executed for assaulting an English soldier who tried to rape her, William Wallace begins a revolt and leads Scottish warriors against the cruel English tyrant who rules Scotland with an iron fist.', 'http://ia.media-imdb.com/images/M/MV5BNjA4ODYxMDU3Nl5BMl5BanBnXkFtZTcwMzkzMTk3OA@@._V1_SX300.jpg', 'R', '24 May 1995', '178 min', 'Braveheart', 'movie', 'Randall Wallace', '1995', '8.4', '694,585'),
('tt0114709', 'Tom Hanks, Tim Allen, Don Rickles, Jim Varney', 'Nominated for 3 Oscars. Another 22 wins & 17 nominations.', 'USA', 'John Lasseter', 'Animation, Adventure, Comedy', 'English', '92', 'A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy''s room.', 'http://ia.media-imdb.com/images/M/MV5BMTgwMjI4MzU5N15BMl5BanBnXkFtZTcwMTMyNTk3OA@@._V1_SX300.jpg', 'G', '22 Nov 1995', '81 min', 'Toy Story', 'movie', 'John Lasseter (original story by), Pete Docter (original story by), Andrew Stanton (original story by), Joe Ranft (original story by), Joss Whedon (screenplay), Andrew Stanton (screenplay), Joel Cohen (screenplay), Alec Sokolow (screenplay)', '1995', '8.3', '574,251'),
('tt0115147', 'Jon Stewart', 'Won 23 Primetime Emmys. Another 27 wins & 115 nominations.', 'USA', 'N/A', 'Comedy, News, Talk-Show', 'English', 'N/A', 'America''s top fake news show.', 'http://ia.media-imdb.com/images/M/MV5BNTg0MzEzMjQ4OV5BMl5BanBnXkFtZTcwNjk5NzkyMQ@@._V1._CR26,5,333,403_SY132_CR10,0,89,132_AL_.jpg_V1_SX300.jpg', 'TV-14', '22 Jul 1996', '30 min', 'The Daily Show', 'series', 'Lizz Winstead, Madeleine Smithberg', '1996â€“', '8.8', '31,031'),
('tt0119217', 'Matt Damon, Robin Williams, Ben Affleck, Stellan SkarsgÃ¥rd', 'Won 2 Oscars. Another 20 wins & 52 nominations.', 'USA', 'Gus Van Sant', 'Drama', 'English', '70', 'Will Hunting, a janitor at M.I.T., has a gift for mathematics, but needs help from a psychologist to find direction in his life.', 'http://ia.media-imdb.com/images/M/MV5BMTk0NjY0Mzg5MF5BMl5BanBnXkFtZTcwNzM1OTM2MQ@@._V1_SX300.jpg', 'R', '09 Jan 1998', '126 min', 'Good Will Hunting', 'movie', 'Matt Damon, Ben Affleck', '1997', '8.3', '562,757'),
('tt0120737', 'Alan Howard, Noel Appleby, Sean Astin, Sala Baker', 'Won 4 Oscars. Another 101 wins & 111 nominations.', 'New Zealand, USA', 'Peter Jackson', 'Adventure, Drama, Fantasy', 'English, Sindarin', '92', 'A meek Hobbit and eight companions set out on a journey to destroy the One Ring and the Dark Lord Sauron.', 'http://ia.media-imdb.com/images/M/MV5BNTEyMjAwMDU1OV5BMl5BanBnXkFtZTcwNDQyNTkxMw@@._V1_SX300.jpg', 'PG-13', '19 Dec 2001', '178 min', 'The Lord of the Rings: The Fellowship of the Ring', 'movie', 'J.R.R. Tolkien (novel), Fran Walsh (screenplay), Philippa Boyens (screenplay), Peter Jackson (screenplay)', '2001', '8.8', '1,160,499'),
('tt0133093', 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving', 'Won 4 Oscars. Another 33 wins & 42 nominations.', 'USA, Australia', 'Andy Wachowski, Lana Wachowski', 'Action, Sci-Fi', 'English', '73', 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', 'http://ia.media-imdb.com/images/M/MV5BMTkxNDYxOTA4M15BMl5BanBnXkFtZTgwNTk0NzQxMTE@._V1_SX300.jpg', 'R', '31 Mar 1999', '136 min', 'The Matrix', 'movie', 'Andy Wachowski, Lana Wachowski', '1999', '8.7', '1,148,739'),
('tt0137523', 'Edward Norton, Brad Pitt, Helena Bonham Carter, Meat Loaf', 'Nominated for 1 Oscar. Another 8 wins & 27 nominations.', 'USA, Germany', 'David Fincher', 'Drama', 'English', '66', 'An insomniac office worker, looking for a way to change his life, crosses paths with a devil-may-care soap maker, forming an underground fight club that evolves into something much, much more...', 'http://ia.media-imdb.com/images/M/MV5BMjIwNTYzMzE1M15BMl5BanBnXkFtZTcwOTE5Mzg3OA@@._V1_SX300.jpg', 'R', '15 Oct 1999', '139 min', 'Fight Club', 'movie', 'Chuck Palahniuk (novel), Jim Uhls (screenplay)', '1999', '8.8', '1,254,308'),
('tt0167260', 'Noel Appleby, Ali Astin, Sean Astin, David Aston', 'Won 11 Oscars. Another 158 wins & 107 nominations.', 'USA, New Zealand', 'Peter Jackson', 'Adventure, Drama, Fantasy', 'English, Quenya, Old English, Sindarin', '94', 'Gandalf and Aragorn lead the World of Men against Sauron''s army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.', 'http://ia.media-imdb.com/images/M/MV5BMjE4MjA1NTAyMV5BMl5BanBnXkFtZTcwNzM1NDQyMQ@@._V1_SX300.jpg', 'PG-13', '17 Dec 2003', '201 min', 'The Lord of the Rings: The Return of the King', 'movie', 'J.R.R. Tolkien (novel), Fran Walsh (screenplay), Philippa Boyens (screenplay), Peter Jackson (screenplay)', '2003', '8.9', '1,147,689'),
('tt0167261', 'Bruce Allpress, Sean Astin, John Bach, Sala Baker', 'Won 2 Oscars. Another 105 wins & 114 nominations.', 'USA, New Zealand', 'Peter Jackson', 'Adventure, Drama, Fantasy', 'English, Sindarin, Old English', '88', 'While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron''s new ally, Saruman, and his hordes of Isengard.', 'http://ia.media-imdb.com/images/M/MV5BMTAyNDU0NjY4NTheQTJeQWpwZ15BbWU2MDk4MTY2Nw@@._V1_SX300.jpg', 'PG-13', '18 Dec 2002', '179 min', 'The Lord of the Rings: The Two Towers', 'movie', 'J.R.R. Tolkien (novel), Fran Walsh (screenplay), Philippa Boyens (screenplay), Stephen Sinclair (screenplay), Peter Jackson (screenplay)', '2002', '8.7', '1,037,590'),
('tt0268978', 'Russell Crowe, Ed Harris, Jennifer Connelly, Christopher Plummer', 'Won 4 Oscars. Another 31 wins & 63 nominations.', 'USA', 'Ron Howard', 'Biography, Drama', 'English', '72', 'After a brilliant but asocial mathematician, John Nash, accepts secret work in cryptography, his life takes a turn for the nightmarish.', 'http://ia.media-imdb.com/images/M/MV5BMTQ4MDI2MzkwMl5BMl5BanBnXkFtZTYwMjk0NTA5._V1_SX300.jpg', 'PG-13', '04 Jan 2002', '135 min', 'A Beautiful Mind', 'movie', 'Akiva Goldsman, Sylvia Nasar (book)', '2001', '8.2', '573,217'),
('tt0361748', 'Brad Pitt, MÃ©lanie Laurent, Christoph Waltz, Eli Roth', 'Won 1 Oscar. Another 117 wins & 143 nominations.', 'USA, Germany', 'Quentin Tarantino, Eli Roth', 'Adventure, Drama, War', 'English, German, French, Italian', '69', 'In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner''s vengeful plans for the same.', 'http://ia.media-imdb.com/images/M/MV5BMjIzMDI4MTUzOV5BMl5BanBnXkFtZTcwNDY3NjA3Mg@@._V1_SX300.jpg', 'R', '21 Aug 2009', '153 min', 'Inglourious Basterds', 'movie', 'Quentin Tarantino', '2009', '8.3', '819,381'),
('tt0364845', 'Michael Weatherly, Pauley Perrette, Mark Harmon, David McCallum', 'Nominated for 3 Primetime Emmys. Another 19 wins & 26 nominations.', 'USA', 'N/A', 'Action, Comedy, Crime', 'English', 'N/A', 'The cases of the Naval Criminal Investigative Service''s Washington DC Major Case Response Team, led by Special Agent Leroy Jethro Gibbs.', 'http://ia.media-imdb.com/images/M/MV5BMTYyMTQ0MTU1OF5BMl5BanBnXkFtZTcwMjI0Njg4Ng@@._V1_SX300.jpg', 'TV-14', '23 Sep 2003', '60 min', 'NCIS', 'series', 'Donald P. Bellisario, Don McGill', '2003â€“', '7.9', '81,442'),
('tt0372784', 'Christian Bale, Michael Caine, Liam Neeson, Katie Holmes', 'Nominated for 1 Oscar. Another 16 wins & 63 nominations.', 'USA, UK', 'Christopher Nolan', 'Action, Adventure', 'English, Urdu, Mandarin', '70', 'After training with his mentor, Batman begins his war on crime to free the crime-ridden Gotham City from corruption that the Scarecrow and the League of Shadows have cast upon it.', 'http://ia.media-imdb.com/images/M/MV5BNTM3OTc0MzM2OV5BMl5BanBnXkFtZTYwNzUwMTI3._V1_SX300.jpg', 'PG-13', '15 Jun 2005', '140 min', 'Batman Begins', 'movie', 'Bob Kane (characters), David S. Goyer (story), Christopher Nolan (screenplay), David S. Goyer (screenplay)', '2005', '8.3', '906,246'),
('tt0386676', 'Rainn Wilson, John Krasinski, Jenna Fischer, Leslie David Baker', 'Won 1 Golden Globe. Another 37 wins & 150 nominations.', 'USA', 'N/A', 'Comedy', 'English', 'N/A', 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium. Based on the hit BBC series.', 'http://ia.media-imdb.com/images/M/MV5BMTgzNjAzMDE0NF5BMl5BanBnXkFtZTcwNTEyMzM3OA@@._V1_SX300.jpg', 'TV-PG', '24 Mar 2005', '22 min', 'The Office', 'series', 'Greg Daniels, Ricky Gervais, Stephen Merchant', '2005â€“2013', '8.8', '186,531'),
('tt0411008', 'Naveen Andrews, Matthew Fox, Jorge Garcia, Josh Holloway', 'Won 1 Golden Globe. Another 84 wins & 333 nominations.', 'USA', 'N/A', 'Adventure, Drama, Fantasy', 'English, Portuguese, Spanish, Arabic, French, Korean, German, Latin, Russian, Japanese', 'N/A', 'The survivors of a plane crash are forced to work together in order to survive on a seemingly deserted tropical island.', 'http://ia.media-imdb.com/images/M/MV5BMjA3NzMyMzU1MV5BMl5BanBnXkFtZTcwNjc1ODUwMg@@._V1_SX300.jpg', 'TV-14', '22 Sep 2004', '44 min', 'Lost', 'series', 'J.J. Abrams, Jeffrey Lieber, Damon Lindelof', '2004â€“2010', '8.5', '354,588'),
('tt0412142', 'Hugh Laurie, Omar Epps, Robert Sean Leonard, Jesse Spencer', 'Won 2 Golden Globes. Another 51 wins & 117 nominations.', 'USA', 'N/A', 'Drama, Mystery', 'English', 'N/A', 'An antisocial maverick doctor who specializes in diagnostic medicine does whatever it takes to solve puzzling cases that come his way using his crack team of doctors and his wits.', 'http://ia.media-imdb.com/images/M/MV5BMjA4NTkzNjg1OF5BMl5BanBnXkFtZTcwNjg3MTI1Ng@@._V1_SX300.jpg', 'TV-14', '16 Nov 2004', '44 min', 'House M.D.', 'series', 'David Shore', '2004â€“2012', '8.8', '285,972'),
('tt0435761', 'Tom Hanks, Tim Allen, Joan Cusack, Ned Beatty', 'Won 2 Oscars. Another 56 wins & 86 nominations.', 'USA', 'Lee Unkrich', 'Animation, Adventure, Comedy', 'English, Spanish', '92', 'The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it''s up to Woody to convince the other toys that they weren''t abandoned and to return home.', 'http://ia.media-imdb.com/images/M/MV5BMTgxOTY4Mjc0MF5BMl5BanBnXkFtZTcwNTA4MDQyMw@@._V1_SX300.jpg', 'G', '18 Jun 2010', '103 min', 'Toy Story 3', 'movie', 'John Lasseter (story), Andrew Stanton (story), Lee Unkrich (story), Michael Arndt (screenplay)', '2010', '8.4', '508,680'),
('tt0440963', 'Matt Damon, Julia Stiles, David Strathairn, Scott Glenn', 'Won 3 Oscars. Another 24 wins & 36 nominations.', 'USA, Germany', 'Paul Greengrass', 'Action, Thriller', 'English, French, Arabic, Russian, Spanish', '85', 'Jason Bourne dodges a ruthless CIA official and his agents from a new assassination program while searching for the origins of his life as a trained killer.', 'http://ia.media-imdb.com/images/M/MV5BMTgzNjMwOTM3N15BMl5BanBnXkFtZTcwMzA5MDY0MQ@@._V1_SX300.jpg', 'PG-13', '03 Aug 2007', '115 min', 'The Bourne Ultimatum', 'movie', 'Tony Gilroy (screenplay), Scott Z. Burns (screenplay), George Nolfi (screenplay), Tony Gilroy (screen story), Robert Ludlum (novel)', '2007', '8.1', '462,097'),
('tt0455275', 'Dominic Purcell, Wentworth Miller, Amaury Nolasco, Robert Knepper', 'Nominated for 2 Golden Globes. Another 4 wins & 24 nominations.', 'USA', 'N/A', 'Action, Crime, Drama', 'English, Spanish', 'N/A', 'Due to a political conspiracy, an innocent man is sent to death row and his only hope is his brother who makes it his mission to deliberately get himself sent to the same prison in order to break the both of them from the inside out.', 'http://ia.media-imdb.com/images/M/MV5BMTg3NTkwNzAxOF5BMl5BanBnXkFtZTcwMjM1NjI5MQ@@._V1_SX300.jpg', 'TV-14', '29 Aug 2005', '44 min', 'Prison Break', 'series', 'Paul Scheuring', '2005â€“2009', '8.5', '303,322'),
('tt0458254', 'Stephen Colbert', 'Won 7 Primetime Emmys. Another 15 wins & 72 nominations.', 'USA', 'N/A', 'Comedy, News, Talk-Show', 'English', 'N/A', 'Satirical newscaster Stephen Colbert provides humorous commentary on the big issues going on in the United States and the rest of the world, with his larger-than-life ego and overly-patriotic spirit along with him every step of the way.', 'http://ia.media-imdb.com/images/M/MV5BMTM1NzE5OTI5NV5BMl5BanBnXkFtZTcwNjY5NTI1MQ@@._V1_SX300.jpg', 'TV-14', '17 Oct 2005', '30 min', 'The Colbert Report', 'series', 'N/A', '2005â€“2015', '8.7', '28,418'),
('tt0460649', 'Josh Radnor, Jason Segel, Cobie Smulders, Neil Patrick Harris', 'Nominated for 2 Golden Globes. Another 21 wins & 72 nominations.', 'USA', 'N/A', 'Comedy, Romance', 'English', 'N/A', 'A father recounts to his children, through a series of flashbacks, the journey he and his four best friends took leading up to him meeting their mother.', 'http://ia.media-imdb.com/images/M/MV5BMTA5MzAzNTcyNjZeQTJeQWpwZ15BbWU3MDUyMzE1MTk@._V1_SX300.jpg', 'TV-14', '19 Sep 2005', '22 min', 'How I Met Your Mother', 'series', 'Carter Bays, Craig Thomas', '2005â€“2014', '8.4', '423,072'),
('tt0468569', 'Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine', 'Won 2 Oscars. Another 141 wins & 126 nominations.', 'USA, UK', 'Christopher Nolan', 'Action, Crime, Drama', 'English, Mandarin', '82', 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the caped crusader must come to terms with one of the greatest psychological tests of his ability to fight injustice.', 'http://ia.media-imdb.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg', 'PG-13', '18 Jul 2008', '152 min', 'The Dark Knight', 'movie', 'Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)', '2008', '9.0', '1,564,829'),
('tt0816692', 'Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow', 'Won 1 Oscar. Another 35 wins & 123 nominations.', 'USA, UK', 'Christopher Nolan', 'Adventure, Drama, Sci-Fi', 'English', '74', 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity''s survival.', 'http://ia.media-imdb.com/images/M/MV5BMjIxNTU4MzY4MF5BMl5BanBnXkFtZTgwMzM4ODI3MjE@._V1_SX300.jpg', 'PG-13', '07 Nov 2014', '169 min', 'Interstellar', 'movie', 'Jonathan Nolan, Christopher Nolan', '2014', '8.6', '821,030'),
('tt0848228', 'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth', 'Nominated for 1 Oscar. Another 35 wins & 76 nominations.', 'USA', 'Joss Whedon', 'Action, Sci-Fi, Thriller', 'English, Russian', '69', 'Earth''s mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.', 'http://ia.media-imdb.com/images/M/MV5BMTk2NTI1MTU4N15BMl5BanBnXkFtZTcwODg0OTY0Nw@@._V1_SX300.jpg', 'PG-13', '04 May 2012', '143 min', 'The Avengers', 'movie', 'Joss Whedon (screenplay), Zak Penn (story), Joss Whedon (story)', '2012', '8.1', '920,458'),
('tt0892769', 'Jay Baruchel, Gerard Butler, Craig Ferguson, America Ferrera', 'Nominated for 2 Oscars. Another 24 wins & 57 nominations.', 'USA', 'Dean DeBlois, Chris Sanders', 'Animation, Adventure, Family', 'English', '74', 'A hapless young Viking who aspires to hunt dragons, becomes the unlikely friend of a young dragon himself, and learns there may be more to the creatures than he assumed.', 'http://ia.media-imdb.com/images/M/MV5BMjA5NDQyMjc2NF5BMl5BanBnXkFtZTcwMjg5ODcyMw@@._V1_SX300.jpg', 'PG', '26 Mar 2010', '98 min', 'How to Train Your Dragon', 'movie', 'William Davies (screenplay), Dean DeBlois (screenplay), Chris Sanders (screenplay), Cressida Cowell (book)', '2010', '8.2', '450,613'),
('tt0898266', 'Johnny Galecki, Jim Parsons, Kaley Cuoco, Simon Helberg', 'Won 1 Golden Globe. Another 49 wins & 161 nominations.', 'USA', 'N/A', 'Comedy', 'English, Hindi, Italian, Russian, Mandarin, Klingon', 'N/A', 'A woman who moves into an apartment across the hall from two brilliant but socially awkward physicists shows them how little they know about life outside of the laboratory.', 'http://ia.media-imdb.com/images/M/MV5BMjI1Mzc4MDUwNl5BMl5BanBnXkFtZTgwMDAzOTIxMjE@._V1_SX300.jpg', 'TV-14', '24 Sep 2007', '22 min', 'The Big Bang Theory', 'series', 'Chuck Lorre, Bill Prady', '2007â€“', '8.4', '496,762'),
('tt0903747', 'Bryan Cranston, Anna Gunn, Aaron Paul, Dean Norris', 'Won 2 Golden Globes. Another 118 wins & 197 nominations.', 'USA', 'N/A', 'Crime, Drama, Thriller', 'English, Spanish', 'N/A', 'A chemistry teacher diagnosed with terminal lung cancer teams up with his former student to cook and sell crystal meth.', 'http://ia.media-imdb.com/images/M/MV5BMTQ0ODYzODc0OV5BMl5BanBnXkFtZTgwMDk3OTcyMDE@._V1_SX300.jpg', 'TV-14', '20 Jan 2008', '47 min', 'Breaking Bad', 'series', 'Vince Gilligan', '2008â€“2013', '9.5', '790,356'),
('tt0944947', 'Peter Dinklage, Lena Headey, Emilia Clarke, Kit Harington', 'Won 1 Golden Globe. Another 134 wins & 288 nominations.', 'USA', 'N/A', 'Adventure, Drama, Fantasy', 'English', 'N/A', 'While a civil war brews between several noble families in Westeros, the children of the former rulers of the land attempt to rise up to power. Meanwhile a forgotten race, bent on destruction, return after thousands of years in the North.', 'http://ia.media-imdb.com/images/M/MV5BMTYwOTEzMDMzMl5BMl5BanBnXkFtZTgwNzExODIzNzE@._V1_SX300.jpg', 'TV-MA', '17 Apr 2011', '56 min', 'Game of Thrones', 'series', 'David Benioff, D.B. Weiss', '2011â€“', '9.5', '906,519'),
('tt0993846', 'Leonardo DiCaprio, Jonah Hill, Margot Robbie, Matthew McConaughey', 'Nominated for 5 Oscars. Another 34 wins & 146 nominations.', 'USA', 'Martin Scorsese', 'Biography, Comedy, Crime', 'English, French', '75', 'Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.', 'http://ia.media-imdb.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX300.jpg', 'R', '25 Dec 2013', '180 min', 'The Wolf of Wall Street', 'movie', 'Terence Winter (screenplay), Jordan Belfort (book)', '2013', '8.2', '704,754'),
('tt1130884', 'Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley, Max von Sydow', '7 wins & 53 nominations.', 'USA', 'Martin Scorsese', 'Mystery, Thriller', 'English, German', '63', 'A U.S Marshal investigates the disappearance of a murderess who escaped from a hospital for the criminally insane.', 'http://ia.media-imdb.com/images/M/MV5BMTMxMTIyNzMxMV5BMl5BanBnXkFtZTcwOTc4OTI3Mg@@._V1_SX300.jpg', 'R', '19 Feb 2010', '138 min', 'Shutter Island', 'movie', 'Laeta Kalogridis (screenplay), Dennis Lehane (novel)', '2010', '8.1', '720,127'),
('tt1187043', 'Aamir Khan, Madhavan, Sharman Joshi, Kareena Kapoor', '25 wins & 13 nominations.', 'India', 'Rajkumar Hirani', 'Comedy, Drama', 'Hindi, English', '67', 'Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently, even as the rest of the world called them "idiots".', 'http://ia.media-imdb.com/images/M/MV5BMTMyOTg0ODQ1OF5BMl5BanBnXkFtZTcwNjc0NTMwNQ@@._V1_SX300.jpg', 'PG-13', '25 Dec 2009', '170 min', '3 Idiots', 'movie', 'Rajkumar Hirani, Abhijat Joshi, Vidhu Vinod Chopra (screenplay)', '2009', '8.4', '186,241'),
('tt1345836', 'Christian Bale, Gary Oldman, Tom Hardy, Joseph Gordon-Levitt', 'Nominated for 1 BAFTA Film Award. Another 44 wins & 98 nominations.', 'USA, UK', 'Christopher Nolan', 'Action, Thriller', 'English', '78', 'Eight years after the Joker''s reign of anarchy, the Dark Knight, with the help of the enigmatic Selia, is forced from his imposed exile to save Gotham City, now on the edge of total annihilation, from the brutal guerrilla terrorist Bane.', 'http://ia.media-imdb.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX300.jpg', 'PG-13', '20 Jul 2012', '164 min', 'The Dark Knight Rises', 'movie', 'Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)', '2012', '8.5', '1,070,247'),
('tt1375666', 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy', 'Won 4 Oscars. Another 138 wins & 192 nominations.', 'USA, UK', 'Christopher Nolan', 'Action, Mystery, Sci-Fi', 'English, Japanese, French', '74', 'A thief who steals corporate secrets through use of the dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.', 'http://ia.media-imdb.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg', 'PG-13', '16 Jul 2010', '148 min', 'Inception', 'movie', 'Christopher Nolan', '2010', '8.8', '1,366,602'),
('tt1392190', 'Tom Hardy, Charlize Theron, Nicholas Hoult, Hugh Keays-Byrne', 'Nominated for 2 Golden Globes. Another 81 wins & 133 nominations.', 'Australia, USA', 'George Miller', 'Action, Adventure, Sci-Fi', 'English, Russian', '89', 'A woman rebels against a tyrannical ruler in post apocalyptic Australia in search for her homeland with the help of a group of female prisoners, a psychotic worshiper, and a drifter named Max.', 'http://ia.media-imdb.com/images/M/MV5BMTUyMTE0ODcxNF5BMl5BanBnXkFtZTgwODE4NDQzNTE@._V1_SX300.jpg', 'R', '15 May 2015', '120 min', 'Mad Max: Fury Road', 'movie', 'George Miller, Brendan McCarthy, Nick Lathouris', '2015', '8.2', '420,369'),
('tt1405406', 'Paul Wesley, Ian Somerhalder, Kat Graham, Candice King', '35 wins & 48 nominations.', 'USA', 'N/A', 'Drama, Fantasy, Horror', 'English', 'N/A', 'A teenage girl is torn between two vampire brothers.', 'http://ia.media-imdb.com/images/M/MV5BMTgzMzg3NDMxOF5BMl5BanBnXkFtZTgwNjUwMjQyNzE@._V1_SX300.jpg', 'TV-14', '10 Sep 2009', '43 min', 'The Vampire Diaries', 'series', 'Julie Plec, Kevin Williamson', '2009â€“', '7.9', '206,717'),
('tt1442437', 'Ed O''Neill, SofÃ­a Vergara, Jesse Tyler Ferguson, Eric Stonestreet', 'Won 1 Golden Globe. Another 99 wins & 270 nominations.', 'USA', 'N/A', 'Comedy', 'English', 'N/A', 'Three different, but related families face trials and tribulations in their own uniquely comedic ways.', 'http://ia.media-imdb.com/images/M/MV5BMTU5MjQ1MTE2Ml5BMl5BanBnXkFtZTgwMDgwMzg5NjE@._V1_SX300.jpg', 'TV-PG', '23 Sep 2009', '22 min', 'Modern Family', 'series', 'Steven Levitan, Christopher Lloyd', '2009â€“', '8.6', '227,872'),
('tt1475582', 'Benedict Cumberbatch, Martin Freeman, Una Stubbs, Rupert Graves', 'Nominated for 1 Golden Globe. Another 70 wins & 103 nominations.', 'UK, USA', 'N/A', 'Crime, Drama, Mystery', 'English', 'N/A', 'A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.', 'http://ia.media-imdb.com/images/M/MV5BNTA2MTE1NDI5OV5BMl5BanBnXkFtZTcwNzM2MzU3Nw@@._V1_SX300.jpg', 'TV-14', '24 Oct 2010', '88 min', 'Sherlock', 'series', 'Mark Gatiss, Steven Moffat', '2010â€“', '9.3', '454,123'),
('tt1504320', 'Colin Firth, Helena Bonham Carter, Derek Jacobi, Robert Portal', 'Won 4 Oscars. Another 96 wins & 182 nominations.', 'UK, USA, Australia', 'Tom Hooper', 'Biography, Drama, History', 'English', '88', 'The story of King George VI of the United Kingdom of Great Britain and Northern Ireland, his impromptu ascension to the throne and the speech therapist who helped the unsure monarch become worthy of it.', 'http://ia.media-imdb.com/images/M/MV5BMzU5MjEwMTg2Nl5BMl5BanBnXkFtZTcwNzM3MTYxNA@@._V1_SX300.jpg', 'R', '25 Dec 2010', '118 min', 'The King''s Speech', 'movie', 'David Seidler (screenplay)', '2010', '8.0', '472,158'),
('tt1520211', 'Andrew Lincoln, Chandler Riggs, Norman Reedus, Melissa McBride', 'Nominated for 1 Golden Globe. Another 42 wins & 122 nominations.', 'USA', 'N/A', 'Drama, Horror, Thriller', 'English', 'N/A', 'Sheriff Deputy Rick Grimes leads a group of survivors in a world overrun by zombies.', 'http://ia.media-imdb.com/images/M/MV5BMTk1MjI1NjI0MV5BMl5BanBnXkFtZTcwODQ5MzA3Mw@@._V1_SX300.jpg', 'TV-14', '31 Oct 2010', '44 min', 'The Walking Dead', 'series', 'Frank Darabont', '2010â€“', '8.6', '577,307'),
('tt1600194', 'Alex O''Loughlin, Scott Caan, Daniel Dae Kim, Grace Park', 'Nominated for 1 Golden Globe. Another 6 wins & 17 nominations.', 'USA', 'N/A', 'Action, Crime, Drama', 'English', 'N/A', 'Steve McGarrett returns home to Oahu, in order to find his father''s killer. The governor offers him the chance to run his own task force (Five-0). Steve''s team is joined by Chin Ho Kelly, Danny "Danno" Williams, and Kono Kalakaua.', 'http://ia.media-imdb.com/images/M/MV5BMTgyNDk4ODk5MF5BMl5BanBnXkFtZTgwNjY5ODc0NjE@._V1_SX300.jpg', 'TV-14', '20 Sep 2010', '42 min', 'Hawaii Five-0', 'series', 'Leonard Freeman, Alex Kurtzman, Peter M. Lenkov, Roberto Orci', '2010â€“', '7.4', '44,099'),
('tt1628033', 'Richard Hammond, Jeremy Clarkson, James May, Ben Collins', '11 wins & 16 nominations.', 'UK', 'N/A', 'Comedy, Talk-Show', 'English', 'N/A', 'Jeremy, Richard and James talk about everything car-related. From new cars to how they''re fueled, this show has it all.', 'http://ia.media-imdb.com/images/M/MV5BMTM2OTYwMjIzOV5BMl5BanBnXkFtZTcwNTMzNTAwMQ@@._V1._CR0,0,317,396_SY132_CR8,0,89,132_AL_.jpg_V1_SX300.jpg', 'N/A', '20 Oct 2002', '60 min', 'Top Gear', 'series', 'N/A', '2002â€“', '8.9', '70,914'),
('tt1663202', 'Leonardo DiCaprio, Tom Hardy, Domhnall Gleeson, Will Poulter', 'Nominated for 12 Oscars. Another 29 wins & 118 nominations.', 'USA', 'Alejandro GonzÃ¡lez IÃ±Ã¡rritu', 'Adventure, Drama, Thriller', 'English, French, Pawnee', '77', 'A frontiersman on a fur trading expedition in the 1820''s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.', 'http://ia.media-imdb.com/images/M/MV5BMjU4NDExNDM1NF5BMl5BanBnXkFtZTgwMDIyMTgxNzE@._V1_SX300.jpg', 'R', '08 Jan 2016', '156 min', 'The Revenant', 'movie', 'Mark L. Smith (screenplay), Alejandro GonzÃ¡lez IÃ±Ã¡rritu (screenplay), Michael Punke (based in part on the novel by)', '2015', '8.3', '86,285'),
('tt1796960', 'Claire Danes, Mandy Patinkin, Rupert Friend, Damian Lewis', 'Won 5 Golden Globes. Another 45 wins & 134 nominations.', 'USA', 'N/A', 'Drama, Mystery, Thriller', 'English', 'N/A', 'When Marine Nicolas Brody is hailed as a hero after he returns home from eight years of captivity in Iraq, intelligence officer Carrie Mathison is the only one who suspects that he may have been turned.', 'http://ia.media-imdb.com/images/M/MV5BMjE0NTc2MzM1OV5BMl5BanBnXkFtZTgwMDk2NjA2NjE@._V1_SX300.jpg', 'TV-MA', '02 Oct 2011', '55 min', 'Homeland', 'series', 'Alex Gansa, Howard Gordon', '2011â€“', '8.4', '214,463'),
('tt1853728', 'Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington', 'Won 2 Oscars. Another 51 wins & 133 nominations.', 'USA', 'Quentin Tarantino', 'Drama, Western', 'English, German, French', '81', 'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.', 'http://ia.media-imdb.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg', 'R', '25 Dec 2012', '165 min', 'Django Unchained', 'movie', 'Quentin Tarantino', '2012', '8.5', '870,792'),
('tt1856010', 'Kevin Spacey, Robin Wright, Michael Kelly, Nathan Darrow', 'Won 2 Golden Globes. Another 15 wins & 123 nominations.', 'USA', 'N/A', 'Drama', 'English', 'N/A', 'A Congressman works with his equally conniving wife to exact revenge on the people who betrayed him.', 'http://ia.media-imdb.com/images/M/MV5BMTY1NDcwMDcxN15BMl5BanBnXkFtZTgwMDI1NTQzNDE@._V1_SX300.jpg', 'TV-MA', '01 Feb 2013', '51 min', 'House of Cards', 'series', 'Beau Willimon', '2013â€“', '9.0', '268,094'),
('tt1870479', 'Jeff Daniels, Emily Mortimer, John Gallagher Jr., Alison Pill', 'Nominated for 2 Golden Globes. Another 8 wins & 29 nominations.', 'USA', 'N/A', 'Drama', 'English', 'N/A', 'A newsroom undergoes some changes in its workings and morals as a new team is brought in, bringing unexpected results for its existing news anchor.', 'http://ia.media-imdb.com/images/M/MV5BMTEyMzc0ODAwMjVeQTJeQWpwZ15BbWU4MDMxODk4OTIx._V1_SX300.jpg', 'TV-MA', '24 Jun 2012', '55 min', 'The Newsroom', 'series', 'Aaron Sorkin', '2012â€“2014', '8.6', '75,442'),
('tt2015381', 'Chris Pratt, Zoe Saldana, Dave Bautista, Vin Diesel', 'Nominated for 2 Oscars. Another 45 wins & 87 nominations.', 'USA, UK', 'James Gunn', 'Action, Adventure, Sci-Fi', 'English', '76', 'A group of intergalactic criminals are forced to work together to stop a fanatical warrior from taking control of the universe.', 'http://ia.media-imdb.com/images/M/MV5BMTAwMjU5OTgxNjZeQTJeQWpwZ15BbWU4MDUxNDYxODEx._V1_SX300.jpg', 'PG-13', '01 Aug 2014', '121 min', 'Guardians of the Galaxy', 'movie', 'James Gunn, Nicole Perlman, Dan Abnett (comic book), Andy Lanning (comic book)', '2014', '8.1', '606,903'),
('tt2024544', 'Chiwetel Ejiofor, Dwight Henry, Dickie Gravois, Bryan Batt', 'Won 3 Oscars. Another 229 wins & 300 nominations.', 'USA, UK', 'Steve McQueen', 'Biography, Drama, History', 'English', '97', 'In the antebellum United States, Solomon Northup, a free black man from upstate New York, is abducted and sold into slavery.', 'http://ia.media-imdb.com/images/M/MV5BMjExMTEzODkyN15BMl5BanBnXkFtZTcwNTU4NTc4OQ@@._V1_SX300.jpg', 'R', '08 Nov 2013', '134 min', '12 Years a Slave', 'movie', 'John Ridley (screenplay), Solomon Northup (based on "Twelve Years a Slave" by)', '2013', '8.1', '401,573'),
('tt2084970', 'Benedict Cumberbatch, Keira Knightley, Matthew Goode, Rory Kinnear', 'Won 1 Oscar. Another 43 wins & 137 nominations.', 'UK, USA', 'Morten Tyldum', 'Biography, Drama, Thriller', 'English, German', '73', 'During World War II, mathematician Alan Turing tries to crack the enigma code with help from fellow mathematicians.', 'http://ia.media-imdb.com/images/M/MV5BNDkwNTEyMzkzNl5BMl5BanBnXkFtZTgwNTAwNzk3MjE@._V1_SX300.jpg', 'PG-13', '25 Dec 2014', '114 min', 'The Imitation Game', 'movie', 'Graham Moore, Andrew Hodges (book)', '2014', '8.1', '394,021'),
('tt2096673', 'Amy Poehler, Phyllis Smith, Richard Kind, Bill Hader', 'Won 1 Golden Globe. Another 28 wins & 77 nominations.', 'USA', 'Pete Docter, Ronnie Del Carmen', 'Animation, Adventure, Comedy', 'English', '94', 'After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school.', 'http://ia.media-imdb.com/images/M/MV5BOTgxMDQwMDk0OF5BMl5BanBnXkFtZTgwNjU5OTg2NDE@._V1_SX300.jpg', 'PG', '19 Jun 2015', '95 min', 'Inside Out', 'movie', 'Pete Docter (original story by), Ronnie Del Carmen (original story by), Pete Docter (screenplay), Meg LeFauve (screenplay), Josh Cooley (screenplay)', '2015', '8.3', '243,897'),
('tt2278388', 'Ralph Fiennes, F. Murray Abraham, Mathieu Amalric, Adrien Brody', 'Won 4 Oscars. Another 115 wins & 204 nominations.', 'USA, Germany, UK', 'Wes Anderson', 'Adventure, Comedy, Drama', 'English, French', '88', 'The adventures of Gustave H, a legendary concierge at a famous hotel from the fictional Republic of Zubrowka between the first and second World Wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.', 'http://ia.media-imdb.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_SX300.jpg', 'R', '28 Mar 2014', '99 min', 'The Grand Budapest Hotel', 'movie', 'Stefan Zweig (inspired by the writings of), Wes Anderson (screenplay), Wes Anderson (story), Hugo Guinness (story)', '2014', '8.1', '423,004'),
('tt2356777', 'Matthew McConaughey, Colin Farrell, Woody Harrelson, Rachel McAdams', 'Nominated for 4 Golden Globes. Another 24 wins & 40 nominations.', 'USA', 'N/A', 'Crime, Drama, Mystery', 'English', 'N/A', 'An anthology series in which police investigations unearth the personal and professional secrets of those involved, both within and outside the law.', 'http://ia.media-imdb.com/images/M/MV5BMTUzNTMwODI1OV5BMl5BanBnXkFtZTgwMDIzMTQ0NTE@._V1_SX300.jpg', 'TV-MA', '12 Jan 2014', '55 min', 'True Detective', 'series', 'Nic Pizzolatto', '2014â€“', '9.1', '300,438'),
('tt2372162', 'Taylor Schilling, Michael Harney, Kate Mulgrew, Danielle Brooks', 'Nominated for 6 Golden Globes. Another 33 wins & 77 nominations.', 'USA', 'N/A', 'Comedy, Crime, Drama', 'English', 'N/A', 'The story of Piper Chapman, a woman in her thirties who is sentenced to fifteen months in prison after being convicted of a decade-old crime of transporting money to her drug-dealing girlfriend.', 'http://ia.media-imdb.com/images/M/MV5BODQ2NjE2NDY3Ml5BMl5BanBnXkFtZTgwNjQxNzA1NTE@._V1_SX300.jpg', 'TV-MA', '11 Jul 2013', '59 min', 'Orange Is the New Black', 'series', 'N/A', '2013â€“', '8.3', '167,631'),
('tt2379713', 'Daniel Craig, Christoph Waltz, LÃ©a Seydoux, Ralph Fiennes', 'Nominated for 1 Golden Globe. Another 2 wins & 11 nominations.', 'UK, USA', 'Sam Mendes', 'Action, Adventure, Thriller', 'English, Spanish, Italian, German, French', '60', 'A cryptic message from Bond''s past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE.', 'http://ia.media-imdb.com/images/M/MV5BMjM2Nzg4MzkwOF5BMl5BanBnXkFtZTgwNzA0OTE3NjE@._V1_SX300.jpg', 'PG-13', '06 Nov 2015', '148 min', 'Spectre', 'movie', 'John Logan (screenplay), Neal Purvis (screenplay), Robert Wade (screenplay), Jez Butterworth (screenplay), John Logan (story), Neal Purvis (story), Robert Wade (story), Ian Fleming (characters)', '2015', '7.0', '161,439'),
('tt2395427', 'Robert Downey Jr., Chris Hemsworth, Mark Ruffalo, Chris Evans', '1 win & 12 nominations.', 'USA', 'Joss Whedon', 'Action, Adventure, Sci-Fi', 'English', '66', 'When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it''s up to Earth''s Mightiest Heroes to stop the villainous Ultron from enacting his terrible plans.', 'http://ia.media-imdb.com/images/M/MV5BMTU4MDU3NDQ5Ml5BMl5BanBnXkFtZTgwOTU5MDUxNTE@._V1_SX300.jpg', 'PG-13', '01 May 2015', '141 min', 'Avengers: Age of Ultron', 'movie', 'Joss Whedon, Stan Lee (Marvel comics), Jack Kirby (Marvel comics)', '2015', '7.6', '370,909'),
('tt2395695', 'Neil deGrasse Tyson, Carl Sagan', 'Won 3 Primetime Emmys. Another 8 wins & 21 nominations.', 'USA', 'N/A', 'Documentary', 'English', 'N/A', 'A documentary series that explores how we discovered the laws of nature and found our coordinates in space and time.', 'http://ia.media-imdb.com/images/M/MV5BMTc5NzgwNDE3N15BMl5BanBnXkFtZTgwNDAxMTY5MTE@._V1._CR51,41,938,1336_SY132_CR2,0,89,132_AL_.jpg_V1_SX300.jpg', 'TV-PG', '09 Mar 2014', '557 min', 'Cosmos: A Spacetime Odyssey', 'series', 'N/A', '2014', '9.4', '47,571'),
('tt2488496', 'Harrison Ford, Mark Hamill, Carrie Fisher, Adam Driver', 'Nominated for 5 Oscars. Another 2 wins & 25 nominations.', 'USA', 'J.J. Abrams', 'Action, Adventure, Fantasy', 'English', '81', 'Three decades after the defeat of the Galactic Empire, a new threat arises. The First Order attempts to rule the galaxy and only a ragtag group of heroes can stop them, along with the help of the Resistance.', 'http://ia.media-imdb.com/images/M/MV5BOTAzODEzNDAzMl5BMl5BanBnXkFtZTgwMDU1MTgzNzE@._V1_SX300.jpg', 'PG-13', '18 Dec 2015', '135 min', 'Star Wars: The Force Awakens', 'movie', 'Lawrence Kasdan, J.J. Abrams, Michael Arndt, George Lucas (based on characters created by)', '2015', '8.4', '390,401'),
('tt2707408', 'Wagner Moura, Boyd Holbrook, Pedro Pascal, Joanna Christie', 'Nominated for 2 Golden Globes. Another 1 nomination.', 'USA', 'N/A', 'Biography, Crime, Drama', 'English, Spanish', 'N/A', 'A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar.', 'http://ia.media-imdb.com/images/M/MV5BMjMyNzA0MTA3NV5BMl5BanBnXkFtZTgwMTYxMTA0NjE@._V1_SX300.jpg', 'TV-MA', '28 Aug 2015', '49 min', 'Narcos', 'series', 'Carlo Bernard, Chris Brancato, Doug Miro, Paul Eckstein', '2015â€“', '9.0', '76,610'),
('tt3170832', 'Brie Larson, Jacob Tremblay, Sean Bridgers, Wendy Crewson', 'Won 1 Golden Globe. Another 51 wins & 97 nominations.', 'Ireland, Canada', 'Lenny Abrahamson', 'Drama', 'English', '86', 'After five-year-old Jack and his mother escape from the enclosed surroundings that Jack has known his entire life, the boy makes a thrilling discovery.', 'http://ia.media-imdb.com/images/M/MV5BMjE4NzgzNzEwMl5BMl5BanBnXkFtZTgwMTMzMDE0NjE@._V1_SX300.jpg', 'R', '25 Nov 2015', '118 min', 'Room', 'movie', 'Emma Donoghue (novel), Emma Donoghue (screenplay)', '2015', '8.3', '15,157'),
('tt3488710', 'Joseph Gordon-Levitt, Guillaume Baillargeon, Ã‰milie Leclerc, Mark Trafford', '1 win & 9 nominations.', 'USA', 'Robert Zemeckis', 'Adventure, Biography, Drama', 'English, French', '70', 'In 1974, high-wire artist Philippe Petit recruits a team of people to help him realize his dream: to walk the immense void between the World Trade Center towers.', 'http://ia.media-imdb.com/images/M/MV5BNTY4MzA4Mzc5Nl5BMl5BanBnXkFtZTgwNDIzMzk5NjE@._V1_SX300.jpg', 'PG', '09 Oct 2015', '123 min', 'The Walk', 'movie', 'Robert Zemeckis (screenplay), Christopher Browne (screenplay), Philippe Petit (book)', '2015', '7.5', '47,717'),
('tt3530232', 'John Oliver, David Kaye', 'Won 1 Primetime Emmy. Another 3 wins & 13 nominations.', 'USA', 'N/A', 'Comedy, News, Talk-Show', 'English', 'N/A', 'Former Daily Show Correspondent John Oliver brings his persona to this new weekly news satire program.', 'http://ia.media-imdb.com/images/M/MV5BNTgyMzIzNDAyM15BMl5BanBnXkFtZTgwMTE1Mzg0MTE@._V1_SX300.jpg', 'TV-MA', '27 Apr 2014', '30 min', 'Last Week Tonight with John Oliver', 'series', 'N/A', '2014â€“', '9.2', '27,218'),
('tt3565344', 'Michael Fassbender, Kate Winslet, Seth Rogen, Jeff Daniels', 'Nominated for 2 Oscars. Another 12 wins & 81 nominations.', 'USA, UK', 'Danny Boyle', 'Biography, Drama', 'English', '82', 'Steve Jobs takes us behind the scenes of the digital revolution, to paint a portrait of the man at its epicenter. The story unfolds backstage at three iconic product launches, ending in 1998 with the unveiling of the iMac.', 'http://ia.media-imdb.com/images/M/MV5BMjE0NTA2MTEwOV5BMl5BanBnXkFtZTgwNzg4NzU2NjE@._V1_SX300.jpg', 'R', '23 Oct 2015', '122 min', 'Steve Jobs', 'movie', 'Aaron Sorkin (screenplay), Walter Isaacson (book)', '2015', '7.5', '31,999'),
('tt4387040', 'Akshay Kumar, Nimrat Kaur, Feryna Wazheir, Pawan Chopra', 'N/A', 'India', 'Raja Menon', 'Drama, History, Thriller', 'Hindi', 'N/A', 'Airlift is an uplifting and entertaining edge-of-the-seat thriller and is the story of the biggest ever human evacuation in the history of mankind.', 'http://ia.media-imdb.com/images/M/MV5BMTAzZmJiOGQtOWM3NS00MDEwLWJiNGEtN2QzMDM3NDJjMWQwXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg', 'N/A', '22 Jan 2016', 'N/A', 'Airlift', 'movie', 'Ritesh Shah, Suresh Nair, Raja Menon, Rahul Nangia', '2016', 'N/A', 'N/A');

-- --------------------------------------------------------

--
-- Table structure for table `rating`
--

CREATE TABLE IF NOT EXISTS `rating` (
  `user` varchar(50) DEFAULT NULL,
  `imdbid` varchar(50) DEFAULT NULL,
  `rating` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `rating`
--

INSERT INTO `rating` (`user`, `imdbid`, `rating`) VALUES
('srinath_reddyk@yahoo.com', 'tt0068646', 4),
('srinath_reddyk@yahoo.com', 'tt0062622', 5),
('test@test.com', 'tt0068646', 4),
('test@test.com', 'tt0062622', 3),
('srinath_reddyk@yahoo.com', 'tt0372784', 5),
('srinath_reddyk@yahoo.com', 'tt0848228', 5);

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE IF NOT EXISTS `user` (
  `email` varchar(50) NOT NULL DEFAULT '',
  `password` varchar(50) DEFAULT NULL,
  `firstName` varchar(50) DEFAULT NULL,
  `lastName` varchar(50) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`email`, `password`, `firstName`, `lastName`, `phone`) VALUES
('srinath_reddyk@yahoo.com', 'password', 'srinath reddy', 'kasarla', '3128748221'),
('test@test.com', 'password', 'tester', 'developer', '3128748222'),
('yashwant@gmail.com', 'password', 'yashwant', 'gandreti', '3128748222');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
